# Generated by Django 3.1.3 on 2021-02-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField()),
                ('typeofmusic', models.CharField(max_length=2)),
                ('size', models.CharField(max_length=1000)),
                ('guestcanpause', models.BooleanField()),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('code', models.CharField(default='', max_length=8, unique=True)),
            ],
        ),
    ]
